language: php

php: 
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - FRAMEWORK_VERSION="4.1.*"
  - FRAMEWORK_VERSION="4.2.*"
  - FRAMEWORK_VERSION="4.3.*@dev"

before_install:
  - composer require illuminate/validation:${FRAMEWORK_VERSION} illuminate/support:${FRAMEWORK_VERSION} --no-update

install: composer install --dev --prefer-dist

script: phpunit